language: php

php:
  - 5.5

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-intl
  - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - app/console cache:warmup --env=prod
  - sleep 5

script:
  - bin/behat --stop-on-failure --verbose